---

- name: Get centos 7 generic cloud image
  get_url:
    url: "{{ vmware_centos7_generic_cloud_images_url }}{{ vmware_centos7_generic_cloud_image }}.raw.tar.gz"
    dest: "{{ vmware_centos7_generic_cloud_image_dir }}/{{ vmware_centos7_generic_cloud_image }}.raw.tar.gz"

- name: Unarchive centos 7 generic cloud image
  unarchive:
    src: "{{ vmware_centos7_generic_cloud_image_dir }}/{{ vmware_centos7_generic_cloud_image }}.raw.tar.gz"
    dest: "{{ vmware_centos7_generic_cloud_image_dir }}"
    remote_src: yes

- name: Ensure user_data_dir exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ vmware_centos7_generic_user_data_dir }}"

- name: Template cloud-init user-data
  template:
    src: user-data.txt.j2
    dest: "{{ vmware_centos7_generic_user_data_dir }}/user-data.txt"

- name: Convert raw centos 7 generic cloud image to vmdk
  command: >
    qemu-img convert -O vmdk {{ vmware_centos7_generic_cloud_image_dir }}/{{ vmware_centos7_generic_cloud_image }}.raw {{ vmware_centos7_generic_cloud_output_dir }}/{{ vmware_centos7_generic_cloud_image }}.vmdk

- name: Write cloud-init user-data to ISO
  command: >
    genisoimage -o {{ vmware_centos7_generic_cloud_output_dir }}/userdata.iso -r {{ vmware_centos7_generic_user_data_dir }}
